config:
  descriptive-link-text: false
# MD013 - line-length
  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div
      - sub
      - sup
globs:
- "posts/**/*.qmd"
- "*.qmd"
ignores:
- "_site/**/*.qmd"
- ".github/ISSUE_TEMPLATE/*.md"
# Fix any fixable errors
fix: true
