config:
# MD013 - line-length
  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div
globs:
- "posts/**/*.qmd"
- "*.qmd"
ignores:
- "_site/**/*.qmd"
# Fix any fixable errors
fix: true
