project:
  type: website
  resources:
    - "*.R"
    - "*.Rmd"
    - "*.jpg"
    - "*.pdf"
    - "*.png"
    - "*.yaml"

website:
  title: "SheffieldR"
  site-url: https://SheffieldR.github.io/
  description: "Shefffield R User Group"
  navbar:
    logo: images/SheffieldRLogo_hex_big.png
    search: true
    right:
      - about.qmd
      - sponsors.qmd
      - resources.qmd
      - slides.qmd
      - codeofconduct.qmd
      - icon: github
        href: https://github.com/SheffieldR
      - icon: twitter
        href: https://twitter.com/Sheffield_R_
      - icon: rss
        href: index.xml
      - icon: mastodon
        href: https://fosstodon.org/@sheffieldr
        rel: me
format:
  html:
    theme: pulse
    css: styles.css
