---
layout: post
title:  "SheffieldR : November Meetup"
date:   2023-11-20 17:30:00 +0000
categories: meetups
image: https://drive.google.com/file/d/1Nc2J4M4ZM-FnsENPvHpPfKrbz4LD9lLd/view?usp=drive_link
excerpt_separator: <!--more-->
---


After October's Reboot, we are back with another Meetup this 20th November for a showcase using Shiny to illuminate the power of data-driven insights. Join us as we delve into the world of interactive data visualization, with hands-on demonstrations, insightful discussions, and practical use cases that will empower you to harness the potential of Shiny in your own projects.

<!--more-->


## Summary:
Join us for an exciting showcase where we'll dive into two innovative R-Shiny projects. The first project introduces the fascinating world of mapping to investigate the dynamics of segregation among neighboring regions, a concept we fondly refer to as "social frontiers." In the second project, we explore economic sectors with a focus on aiding South Yorkshire's mayoral authority in their strategic growth planning endeavors.

The burning question that currently occupies our minds: How can we leverage powerful tools like Shiny to assist other institutions, including local councils and mayoral offices, in streamlining their data analysis processes and preventing unnecessary duplication of effort? Be a part of this engaging exploration and discover how Shiny can be a game-changer in data analysis for various institutions. Don't miss this opportunity to be part of the conversation and gain valuable insights into the future of data-driven decision-making.

Bio: Dr Dan Olner is a policy fellow with Y-PERN, the "Yorkshire Policy Engagement and Research Network", working closely with SMYCA in their business, growth and skills team on all things spatial, data and regional. His background is in spatial analysis, spatial economics, data science and politics. He has an interest in using data analysis to address sustainability and net zero issues. More info at [Danoler](https://danolner.net)! 

You can view the slides that will be presented [here](https://ns-rse.github.io/SheffieldR-quarto-for-slides/)

If you have any questions or inquires please get in touch with [Grace Accad](mailto:g.accad@sheffield.ac.uk) or [Neil Shephard](mailto:n.shephard@sheffield.ac.uk)

